### ISSUE TITLE
Application with a virus!

### ISSUE THREAD

**Issue by Operrr** [unlimitedbacon/stl-thumb#37]
There is a downloader trojan in the app. I checked it on a test Windows, not only does the application not work so it installed Marlin3DprinterTools, you never know what malware can be installed without your knowledge. The author, clarify the situation and not deleting posts, or should I ask this question in a video on Youtube?

**Comment by unlimitedbacon** [comment]
The program is not intentionally doing anything malicious. You don't need to take my word for it. Since stl-thumb is open source, you can easily verify this yourself by looking through the source code. Stl-thumb is not a complicated program, so this would not take long. If you wish to examine the code for the Windows installer package, you can also find that here. https://github.com/unlimitedbacon/STLThumbWindows

It is possible that the published release files were unintentionally infected somehow, but this seems unlikely since the Windows builds are done through Appveyor continuous integration, which spins up a new VM for each build. Even if my local machine was infected it would not spread because the published files do not come from my machine.

Please provide documentation of the specific behaviors you have observed that indicate a trojan. Here are some examples of what would be helpful in identifying and isolating malicious code.

- A packet trace of suspicious network activity
- A comparison between a clean build from source and the published files, showing some difference
- A disassembly or hex dump showing the presence of some known virus executable

**Comment by Operrr** [comment]
I checked with the virustotal service. he discovered the trojan TrojanDownloader.Script.iam. Windows10 is blocking boot too

**Comment by unlimitedbacon** [comment]
That is obviously a false positive. VirusTotal is a service that aggregates the results from many other companies antivirus engines. If you look at [the results on VirusTotal](https://www.virustotal.com/gui/file/96b0e8dbdc81de6aa60b5b88fa77e6250e09fa7c7cdbf89bcc27c3d9b3c8458c/detection), 68 of the 69 antivirus tools they use report that the Windows installer package for stl-thumb is clean. An obscure Chinese antivirus called Jiangmin detects something called "TrojanDownloader.Script.iam", but I cannot find any information on a virus by that name whatsoever. There are literally [no results in a Google search](https://www.google.com/search?hl=en&q=%22TrojanDownloader.Script.iam%22). It is extremely common for antivirus tools to detect false positives. You should only use antivirus programs as an indicator that a virus might be present, not as proof.

In any case, you do not need to trust me and you do not need to trust the antivirus scanners either. Stl-thumb is open source so you have everything you need to do your own audit and make your own independent conclusion about whether or not the program does anything malicious.
