### ISSUE TITLE
Setup Failed: Another Version Of this Product Is Already Installed.

### ISSUE THREAD

**Issue by E-Studios** [unlimitedbacon/stl-thumb#45]
Like the title says, an error message says the software is already installed.

Here is what I did, because i had a slicer generating stl thumbnails too I uninstalled STL-Thumb and the slicer.

Now when i want to install STL-Thumb i get this error message.
I'am not able to find anything in the registry either.

![install-error](https://user-images.githubusercontent.com/23241521/131759721-fcef4299-40b3-49e4-8d98-32cca0415762.png)

**Comment by unlimitedbacon** [comment]
Ugh. This kind of garbage is why I hate Windows so much. It still doesn't even have a real package manager.

Some googling suggests this might be because a conflicting version of the MSVC 2015 redistributable is installed. Try going into Add/Remove programs and uninstall "Microsoft Visual C++ 2015 Redistributable".
