### ISSUE TITLE
Empty/white thumbnails unless -x is used

### ISSUE THREAD

**Issue by pastapojken** [unlimitedbacon/stl-thumb#8]
Hi!

I've installed this through the AUR and it only kind of works, the generated thumbnails are always white unless the "-x" option is passed to stl-thumb (this happens in both the command line and through my file manager, pcmanfm).
Not a  huge deal but a bit annoying :)

**Comment by unlimitedbacon** [comment]
I've started running into this problem as well. Without `-x`, stl-thumb tries to use a headless gl context. This was working before, but seems to have stopped for some reason. Maybe a Mesa update broke it.

**Comment by unlimitedbacon** [comment]
I updated some crates and got this working again. If you have a chance, could you try building from source and making sure it is fixed for you as well?

**Comment by pastapojken** [comment]
Yes, fixed!

**Comment by MessedUpHare** [comment]
Please could you update the releases section on github to reflect the changes in commit f60e7f390112e1614c56c073c014f20e936f746f (version 0.3.0) - then I can ask the package maintainer in the AUR to bump their version.

**Comment by MessedUpHare** [comment]
oh - you are the maintainer.. d'oh!.. I'm getting this issue and it looks like you've fixed it in a commit that's ahead of the current 0.2.0 commit.

**Comment by unlimitedbacon** [comment]
I haven't made a release because the issue isn't really fixed. The commit you referenced only fixes it in some situations, but breaks it in others. This is a much more complicated issue than I thought initially.

The problem is that drawing to an off screen framebuffer is failing for some reason when using the OSMesa software renderer. It needs to work with OSMesa because Gnome Files (Nautilus) sandboxes the thumbnailer programs, and the OSMesa renderer is the only one available in that environment. If I did a release it would be broken for anyone using Gnome, and it also needs some tweaks to not break Windows as well.

The current release version (0.2.0) still works fine on distros besides Arch. I suspect this is because Mesa broke something recently, and only Arch has the latest version.

Unfortunately this is beyond my ability to debug. I am using a library called glium to handle the actual OpenGL stuff. I have filed a bug upstream with them (https://github.com/glium/glium/issues/1725).
However, glium is no longer under active development, so I don't expect them to do anything about this.

My only idea right now is to ditch glium entirely and just use raw OpenGL calls. This would defeat the purpose of using Rust, and I don't know if it would even solve the problem, but it might provide a better understanding of what is going wrong.

**Comment by MessedUpHare** [comment]
I've made a workaround by making a bash script in /usr/bin/stl-thumb.sh:
```
export MESA_GL_VERSION_OVERRIDE=4.1COMPAT
stl-thumb -s "$1" "$2" "$3"
```
I also modified a line at /usr/share/thumbnailers/stl-thumb.thumbnailer
```
Exec=stl-thumb.sh %s %i %o
```
...

Really enjoying being able to preview my STL library - thanks for this thumbnailer.

**Comment by unlimitedbacon** [comment]
Interesting. I can make the program request a specific OpenGL version. How did you know that `4.1COMPAT` would work?

**Comment by MessedUpHare** [comment]
I didn't. Unfortunately it wasn't very scientific. Given you said that it worked on non-arch systems, I assumed it was a GL version incompatibility with the library/framework you mentioned.
It's something I have to do now and then to get native (and admittedly proprietary) video games to run on Arch.
So I just worked down through older version numbers until it worked for me.
If you don't have the same issue on other systems, I think it's worth leaving it as a wrapper script as it is a hack. I guess it could be used to assist finding whatever bug exists in the library but as you said it's been abandoned, not sure how successful that would be.
Sorry I couldn't be of more help.

**Comment by unlimitedbacon** [comment]
I am forcing Mesa to use OpenGL 2.1 now. This is the only version I could find that is working across all the platforms I tested.

New version released and the AUR package has been updated. Reopen this if you are still having issues.

**Comment by naikymen** [comment]
Hi! Sorry to necro this. Installing `stl-thumb` from the AUR showed this issue, but compiling froun source with `stl-thumb-git` worked immediately. Thanks for your work!
